name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup set profile minimal
      - run: rustup show
      - run: cargo check --all

  bench:
    name: Compile Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup set profile minimal
      - run: rustup show
      - run: cargo bench --no-run

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup set profile minimal
      - run: rustup show
      - run: cargo test --all

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup set profile minimal
      - run: rustup show
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup set profile minimal
      - run: rustup show
      - run: rustup component add clippy
      - run: cargo clippy --all -- --deny warnings --allow clippy::unknown-clippy-lints
